#def pod
apiVersion: v1
kind: Pod
metadata:
  name: web-appliaction
spec:
  # mutlicontainer pod
  containers:
  - name: user
    image: nginx
    # daemon  pay service
  - name: logs
    image: almalinux
    command: ["sleep","100000000"]
     # daemon cart
