#def pod
apiVersion: v1
kind: Pod
metadata:
  name: web-application
spec:
  # multi-container pod
  containers:
  - name: user
    image: nginx
    # daemon payment service
  - name: logs
    image: almalinux
    command: [ "sleep", "100000000" ] # daemon cart
