apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    environment: productions
    project: roboshop
    component: backend
    app: nodejs
spec:
  containers:
  - name: label-pod-c1
    image: nginx
