apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: mongodb
      value: "vsvicky.mongdb.site"
    - name: catalogue
      value: "vsvicky.catalogue.site"
