apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    project: roboshop
    environment: prod
    tier: backend

spec:
  selector:
    # pod labels
    app: philips
    company: wipro
    project: roboshop
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    app: philips
    company: wipro
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
