apiVersion: v1
kind: Service
metadata:
  name: my-service-np
spec:
  selector:
    app: my-app
    project: roboshop
    tier: backend
  # labels of the pods that this service should target
  ports:
  - protocol: TCP
    port: 80 # service
    targetPort: 80 # container port
---

apiVersion: v1
kind: Pod
metadata:
  name: service-pod-np
  labels:
    app: my-app
    project: roboshop
    tier: backend
spec:
  containers:
  - name: my-container
    image: nginx
