# Important: ReplicaSet pods are managed by selector labels, not by name.
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-ds
  labels:
    app: backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      project: roboshop
      purpose: replicas-demo
  template:
  #pod defination
    metadata:
      labels:
        env: dev
        project: roboshop
        purpose: replicas-demo
    spec:
      containers:
        - name: nginx-dp
          image: nginx:stable-perl


# Commands:
#   kubectl get rs
#   kubectl describe rs nginx-rp